# -*- coding: utf-8 -*-
"""LogiBots_1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B6tvOXTO00QwGYzwOznhDGQt-flHius1
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import joblib  # For saving/loading models
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score, classification_report

# Mount Google Drive (if needed)
from google.colab import drive
drive.mount('/content/drive')

# Load the dataset (Replace 'your_dataset.csv' with actual file path)
df = pd.read_csv('/content/drive/MyDrive/LogiBot/Final_CO__Emission___Maintenance_Prediction_Dataset.csv')

# Drop Vehicle_ID since it's not useful for predictions
df = df.drop(columns=['Vehicle_ID'])

### 1️⃣ CO₂ Emission Prediction Model 🌍 ###
# Define features and target variable
X_co2 = df.drop(columns=['CO2_Emissions_KG', 'Maintenance_Flag'])  # Features
y_co2 = df['CO2_Emissions_KG']  # Target variable

# Split into training (80%) and testing (20%)
X_train_co2, X_test_co2, y_train_co2, y_test_co2 = train_test_split(X_co2, y_co2, test_size=0.2, random_state=42)

# Train the Random Forest Regressor
co2_model = RandomForestRegressor(n_estimators=100, random_state=42)
co2_model.fit(X_train_co2, y_train_co2)

# Make predictions
y_pred_co2 = co2_model.predict(X_test_co2)

# Evaluate model
mae_co2 = mean_absolute_error(y_test_co2, y_pred_co2)
mse_co2 = mean_squared_error(y_test_co2, y_pred_co2)
r2_co2 = r2_score(y_test_co2, y_pred_co2)

print(f"🚀 CO₂ Model Performance:")
print(f"MAE: {mae_co2}")
print(f"MSE: {mse_co2}")
print(f"R² Score: {r2_co2}")

# Save the CO₂ Prediction Model
joblib.dump(co2_model, '/content/drive/MyDrive/CO2_Prediction_Model.pkl')
print("✅ CO₂ Model saved successfully!")

### 2️⃣ Predictive Maintenance Model ⚙️ ###
# Define features and target variable
X_maint = df.drop(columns=['CO2_Emissions_KG', 'Maintenance_Flag'])  # Features
y_maint = df['Maintenance_Flag']  # Target variable

# Split into training (80%) and testing (20%)
X_train_maint, X_test_maint, y_train_maint, y_test_maint = train_test_split(X_maint, y_maint, test_size=0.2, random_state=42)

# Train the Random Forest Classifier
maint_model = RandomForestClassifier(n_estimators=100, random_state=42)
maint_model.fit(X_train_maint, y_train_maint)

# Make predictions
y_pred_maint = maint_model.predict(X_test_maint)

# Evaluate model
accuracy_maint = accuracy_score(y_test_maint, y_pred_maint)
report_maint = classification_report(y_test_maint, y_pred_maint)

print(f"🚀 Maintenance Model Performance:")
print(f"Accuracy: {accuracy_maint}")
print(f"Classification Report:\n{report_maint}")

# Save the Maintenance Prediction Model
joblib.dump(maint_model, '/content/drive/MyDrive/Maintenance_Prediction_Model.pkl')
print("✅ Maintenance Model saved successfully!")

import joblib
import pandas as pd

# Load saved models
co2_model = joblib.load('/content/drive/MyDrive/CO2_Prediction_Model.pkl')
maint_model = joblib.load('/content/drive/MyDrive/Maintenance_Prediction_Model.pkl')

# Define feature names (Make sure it matches the training dataset)
feature_names = [
    "Fuel_Consumption_L",
    "Distance_Travelled_KM",
    "Average_Speed_KMH",
    "Traffic_Congestion_Level",
    "Engine_Temperature_C",
    "Brake_Wear_Level_%",
    "Tire_Pressure_PSI",
    "Vibration_Level_G"
]

# Example input data (Replace with real values)
sample_input = [[484.1724052891073,1944.728317938926,51.60348720176066,8.978172183937332,91.75683881194884,53.21856692979357,48.25476842723873,4.733255410814104

]]  # Sample truck data

# Convert input to DataFrame with feature names
sample_df = pd.DataFrame(sample_input, columns=feature_names)

# Predict CO₂ emissions
co2_prediction = co2_model.predict(sample_df)
print(f"🔵 Predicted CO₂ Emissions: {co2_prediction[0]} kg")

# Predict maintenance need
maintenance_prediction = maint_model.predict(sample_df)
print(f"🔴 Maintenance Needed? {'Yes' if maintenance_prediction[0] == 1 else 'No'}")

# Define feature names (Make sure it matches the training dataset)
feature_names = [
    "Fuel_Consumption_L",
    "Distance_Travelled_KM",
    "Average_Speed_KMH",
    "Traffic_Congestion_Level",
    "Engine_Temperature_C",
    "Brake_Wear_Level_%",
    "Tire_Pressure_PSI",
    "Vibration_Level_G"
]

# Example input data (Replace with real values)
sample_input = [[
145.5248818784815,4981.20209653429,65.00349217893778,4.47540326734439,111.1634326557386,29.978889057734328,30.696079701912517,2.3359746301166853
]]  # Sample truck data

# Convert input to DataFrame with feature names
sample_df = pd.DataFrame(sample_input, columns=feature_names)

# Predict CO₂ emissions
co2_prediction = co2_model.predict(sample_df)
print(f"🔵 Predicted CO₂ Emissions: {co2_prediction[0]} kg")

# Predict maintenance need
maintenance_prediction = maint_model.predict(sample_df)
print(f"🔴 Maintenance Needed? {'Yes' if maintenance_prediction[0] == 1 else 'No'}")

